# SPDX-License-Identifier: MIT
#
# Docker file for client-side component of COMP4000 experience 1.
# Copyright (c) 2021  William Findlay
#
# September 16, 2021  William Findlay  Created this.

FROM busybox

WORKDIR /client
COPY client/getfacts.sh .
RUN chmod +x /client/getfacts.sh

ENTRYPOINT ["/client/getfacts.sh"]

# vim:ft=dockerfile
