# SPDX-License-Identifier: MIT
#
# Docker file for client-side component of COMP4000 experience 1.
# Copyright (c) 2021  William Findlay
#
# September 16, 2021  William Findlay  Created this.

FROM alpine

RUN apk update
RUN apk add curl

WORKDIR /client
COPY client/getfacts.sh .
RUN chmod +x /client/getfacts.sh

RUN echo 'silent' > "$HOME/.curlrc"

CMD ["sleep", "infinity"]

# vim:ft=dockerfile
